[workspace]
resolver = "2"
members = [
    "common",
    "host",
    "host/examples/cpal",
    "plugin",
    "plugin/examples/gain",
    "plugin/examples/polysynth",
    "plugin/examples/xtask",
    "extensions",
    "test-host",
]

[workspace.dependencies]
clack-common = { path = "./common", version = "0.1.0" }
clack-plugin = { path = "./plugin", version = "0.1.0" }
clack-host = { path = "./host", version = "0.1.0", default-features = false }
clack-extensions = { path = "./extensions", version = "0.1.0" }
clack-test-host = { path = "./test-host", version = "0.1.0" }

clap-sys = { git = "https://github.com/glowcoil/clap-sys.git", rev = '22afeff171abab7c702c599b41bedd060de61880', version = "0.3.0" }
selfie = { git = 'https://github.com/prokopyl/selfie', rev = '726013fc94835b6f24918ba822a49e5c3b2a3b25', version = "0.0.2" }

bitflags = "1.3.2"
libloading = "0.8.1"
raw-window-handle = "0.5.2"
stable_deref_trait = "1.2.0"
