all-features = true

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"

allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016"
]

exceptions = [
    # Only used in clack-host-cpal example, the executable is not distrubuted
    { allow = ["MPL-2.0"], name = "option-ext" }
]

[bans]
multiple-versions = "deny"
wildcards = "deny"

skip-tree = [
    # This is just an example, it doesn't matter if there are duplicate dependencies in the build.
    { name = "clack-host-cpal" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
# List of URLs for allowed Git repositories
allow-git = [
    "https://github.com/glowcoil/clap-sys",
    "https://github.com/prokopyl/selfie",

    # for nih_plug_xtask
    "https://github.com/robbert-vdh/nih-plug.git",
    "https://github.com/nicokoch/reflink.git",
]

